const STORAGE_KEY="apostado-sinuca-v1",MAX_PLAYERS=5,SAVED_KEY="apostado-sinuca-jogadores-v1";const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});const state=loadState();
let savedPlayers=loadSavedPlayers();
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const d=JSON.parse(raw);return{players:Array.isArray(d.players)?d.players:[],history:Array.isArray(d.history)?d.history:[],nextMatch:Number(d.nextMatch)||1,bet:Number(d.bet)||10}}}catch(e){}return{players:[],history:[],nextMatch:1,bet:10}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function loadSavedPlayers(){try{const raw=localStorage.getItem(SAVED_KEY);if(raw){const list=JSON.parse(raw);if(Array.isArray(list))return list.filter(p=>p&&p.id&&p.name).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"))}}catch(e){}return[]}
function saveSavedPlayers(){localStorage.setItem(SAVED_KEY,JSON.stringify(savedPlayers));render()}
function isInQueue(name){return state.players.some(p=>p.name.toLowerCase()===name.toLowerCase())}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function getStats(){const stats={};state.history.forEach(g=>{for(const n of[g.p1,g.p2]){stats[n]??={wins:0,losses:0,games:0}}stats[g.winner]??={wins:0,losses:0,games:0};stats[g.loser]??={wins:0,losses:0,games:0};stats[g.p1].games++;stats[g.p2].games++;stats[g.winner].wins++;stats[g.loser].losses++});return stats}
function render(){const p1=state.players[0],p2=state.players[1],stats=getStats();document.getElementById("matchNumber").textContent="Jogo #"+String(state.nextMatch).padStart(3,"0");document.getElementById("currentBet").textContent=money.format(state.bet);document.getElementById("betInput").value=state.bet.toFixed(2);document.getElementById("playerCount").textContent=state.players.length+"/5";document.getElementById("waitingCount").textContent=Math.max(0,state.players.length-2);document.getElementById("totalMatches").textContent=state.history.length;document.getElementById("totalWins").textContent=state.history.length;document.getElementById("totalMoney").textContent=money.format(state.history.reduce((s,g)=>s+g.bet,0));const st=document.getElementById("matchStatus");st.textContent=p1&&p2?"Em andamento":"Aguardando";st.className="status "+(p1&&p2?"status-live":"status-waiting");document.getElementById("matchHint").textContent=p1&&p2?"Registre o vencedor. Ele permanece e o próximo da fila entra no lugar de quem perdeu.":"Cadastre pelo menos 2 jogadores para iniciar.";document.getElementById("playersOnTable").innerHTML=[p1,p2].map((p,i)=>p?'<div class="player-slot active"><span class="position">JOGADOR '+(i+1)+'</span><span class="name">'+esc(p.name)+'</span><span class="record">'+(stats[p.name]?.wins||0)+' vitória(s) • '+(stats[p.name]?.losses||0)+' derrota(s)</span></div>':'<div class="player-slot empty-slot">Vaga '+(i+1)+' disponível</div>').join("");document.getElementById("winPlayer1").disabled=!p1||!p2;document.getElementById("winPlayer2").disabled=!p1||!p2;renderQueue(stats);renderSavedPlayers();renderRanking(stats);renderHistory()}
function renderSavedPlayers(){const el=document.getElementById("savedPlayersList");if(!savedPlayers.length){el.innerHTML='<div class="empty-state">Nenhum jogador cadastrado ainda. Cadastre o primeiro acima.</div>';return}el.innerHTML=savedPlayers.map(p=>{const inQueue=isInQueue(p.name);return '<div class="saved-player '+(inQueue?"in-queue":"")+'"><div class="saved-player-main"><span class="saved-avatar">🎱</span><div><div class="queue-name">'+esc(p.name)+'</div><div class="queue-state">'+(inQueue?"Já está na fila":"Disponível para entrar")+'</div></div></div><div class="saved-actions">'+(inQueue?'<span class="in-label">NA FILA</span>':'<button class="btn btn-small btn-primary" type="button" data-add-saved="'+p.id+'">Adicionar</button>')+'<button class="remove-saved" type="button" data-delete-saved="'+p.id+'" title="Excluir cadastro">✕</button></div></div>'}).join("")}
function renderQueue(stats){document.getElementById("queueList").innerHTML=state.players.length?state.players.map((p,i)=>'<div class="queue-item '+(i<2?"active":"")+'"><span class="queue-number">'+(i+1)+'</span><div class="queue-main"><div class="queue-name">'+esc(p.name)+'</div><div class="queue-state">'+(i===0?"Mesa • jogador 1":i===1?"Mesa • jogador 2":"Aguardando entrada")+' • '+(stats[p.name]?.wins||0)+' vitória(s)</div></div><button class="remove-btn" type="button" data-remove="'+p.id+'">✕</button></div>').join(""):'<div class="empty-state">Nenhum jogador cadastrado.</div>'}
function renderRanking(stats){const arr=Object.entries(stats).sort((a,b)=>b[1].wins-a[1].wins||b[1].games-a[1].games);document.getElementById("rankingList").innerHTML=arr.length?arr.map(([n,s],i)=>'<div class="ranking-row"><span class="rank">#'+(i+1)+'</span><div><div class="person">'+esc(n)+'</div><div class="sub">'+s.games+' partida(s) • '+s.losses+' derrota(s)</div></div><div class="score"><strong>'+s.wins+'</strong><small>vitórias</small></div></div>').join(""):'<div class="empty-state">Nenhum resultado ainda.</div>'}
function renderHistory(){document.getElementById("historyList").innerHTML=state.history.length?state.history.slice().reverse().map(g=>'<div class="history-row"><div><strong>#'+String(g.number).padStart(3,"0")+'</strong><div class="sub">'+new Date(g.time).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})+'</div></div><div><div><span class="win">'+esc(g.winner)+'</span> venceu <span class="loss">'+esc(g.loser)+'</span></div><div class="sub">Aposta: '+money.format(g.bet)+'</div></div><div class="score"><strong>'+money.format(g.bet)+'</strong></div></div>').join(""):'<div class="empty-state">As partidas aparecerão aqui.</div>'}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2200)}
function addPlayer(name){name=name.trim();if(!name)return;if(state.players.length>=MAX_PLAYERS){toast("A fila já está com 5 jogadores.");return}if(isInQueue(name)){toast("Esse jogador já está na fila.");return}let saved=savedPlayers.find(p=>p.name.toLowerCase()===name.toLowerCase());if(!saved){saved={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())),name};savedPlayers.push(saved);savedPlayers.sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));localStorage.setItem(SAVED_KEY,JSON.stringify(savedPlayers))}state.players.push({id:saved.id,name:saved.name});save();toast(name+" entrou na fila.")}
function registerSaved(name){addPlayer(name)}
function deleteSaved(id){const saved=savedPlayers.find(p=>p.id===id);if(!saved)return;if(isInQueue(saved.name)){toast("Retire o jogador da fila antes de excluir.");return}if(confirm("Excluir "+saved.name+" do cadastro?")){savedPlayers=savedPlayers.filter(p=>p.id!==id);saveSavedPlayers();toast("Jogador excluído do cadastro.")}}
function registerWinner(index){const p1=state.players[0],p2=state.players[1];if(!p1||!p2)return;const bet=Math.max(0,Number(state.bet)||0),winner=index===0?p1:p2,loser=index===0?p2:p1;state.history.push({number:state.nextMatch,p1:p1.name,p2:p2.name,winner:winner.name,loser:loser.name,bet,time:new Date().toISOString()});state.nextMatch++;state.players.splice(index===0?1:0,1);save();toast(winner.name+" venceu! Próximo jogador entrou na mesa.")}
document.getElementById("playerForm").addEventListener("submit",e=>{e.preventDefault();const i=document.getElementById("playerName");addPlayer(i.value);i.value="";i.focus()});
document.getElementById("betInput").addEventListener("change",e=>{state.bet=Math.max(0,Number(e.target.value)||0);save()});
document.getElementById("winPlayer1").addEventListener("click",()=>registerWinner(0));document.getElementById("winPlayer2").addEventListener("click",()=>registerWinner(1));
document.getElementById("savedPlayersList").addEventListener("click",e=>{const add=e.target.closest("[data-add-saved]");if(add){const p=savedPlayers.find(x=>x.id===add.dataset.addSaved);if(p)registerSaved(p.name);return}const del=e.target.closest("[data-delete-saved]");if(del)deleteSaved(del.dataset.deleteSaved)});
document.getElementById("queueList").addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(!b)return;state.players=state.players.filter(p=>p.id!==b.dataset.remove);save();toast("Jogador removido.")});
document.getElementById("clearHistoryBtn").addEventListener("click",()=>{if(state.history.length&&confirm("Deseja apagar todo o histórico?")){state.history=[];state.nextMatch=1;save();toast("Histórico limpo.")}});
document.getElementById("newSessionBtn").addEventListener("click",()=>{if(confirm("Começar uma nova rodada? Isso limpa jogadores, histórico e placar.")){state.players=[];state.history=[];state.nextMatch=1;save();toast("Nova rodada iniciada.")}});
render();